# TODO: Round this stuff out so we cover everything important enough.

# Pointblank validation functions ----

#' Run pointblank validation on an eData table
#'
#' Applies pointblank validation rules to check data quality and schema
#' compliance for eData format tables. Can operate in two modes:
#' - Agent mode (agent = TRUE): Creates an agent for reporting and interrogation
#' - Pipeline mode (agent = FALSE): Returns validated data directly for use in pipelines
#'
#' @param data Data frame to validate
#' @param table_name Name of the table being validated (for reporting)
#' @param validation_steps Function that takes a data frame or agent and returns
#'   it with validation steps added. Should be a function like:
#'   `function(x) { x |> col_vals_not_null(...) |> ... }`
#' @param agent Logical. If TRUE (default), returns a pointblank agent object.
#'   If FALSE, returns the validated data with validation failures removed.
#' @param actions Action levels for pointblank agent (only used when agent = TRUE)
#'
#' @return If agent = TRUE, a pointblank agent object containing validation results.
#'   If agent = FALSE, the input data with validation failures removed.
#'
#' @details
#' In agent mode, the agent object can be used to:
#' - Extract validation results with `get_sundered_data()`
#' - Generate reports with `get_agent_report()`
#' - Check pass/fail status
#'
#' In pipeline mode, failed rows are automatically removed from the data.
#'
#' @importFrom pointblank create_agent interrogate action_levels get_agent_report
#' @importFrom glue glue
#' @export
pb_validate_edata_table <- function(
  data,
  table_name,
  validation_steps,
  agent = TRUE,
  actions = action_levels()
) {
  if (agent) {
    # Agent mode: create agent, apply validations, and interrogate ----
    data |>
      create_agent(
        label = glue("eData {table_name} Validation"),
        actions = actions
      ) |>
      validation_steps() |>
      interrogate()
  } else {
    # Pipeline mode: apply validation steps directly to data ----
    data |>
      validation_steps()
  }
}

# ## Campaign validation ----

#' @importFrom pointblank col_vals_not_null col_vals_between rows_distinct action_levels col_vals_lte
#' @export
pb_validate_campaign <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # # Check CAMPAIGN_NAME_SHORT and CAMPAIGN_NAME are not blank
      col_vals_not_null(
        label = "Check CAMPAIGN_NAME_SHORT and CAMPAIGN_NAME are not blank",
        columns = c(CAMPAIGN_NAME_SHORT, CAMPAIGN_NAME),
        actions = actions
      ) |>

      # does core id match file name?
      # currently we just match the date, because the formats are different
      # FIXME: Doesn't work!
      # col_vals_equal(
      #   columns = CAMPAIGN_NAME_SHORT,
      #   value = vars(expected_year),
      #   preconditions = ~ . |>
      #     dplyr::filter(!str_detect(CAMPAIGN_NAME_SHORT, "Vm")) |>
      #     dplyr::mutate(expected_year = str_extract(source_file, "\\d{4}")),
      #   actions = actions
      # ) |>

      # # Check no repeated campaigns
      rows_distinct(
        label = "Check each CAMPAIGN_NAME_SHORT and CAMPAIGN_NAME is unique",
        columns = c(CAMPAIGN_NAME_SHORT, CAMPAIGN_NAME)
      ) |>

      # # Check CAMPAIGN_START_DATE is between 01 Jan 1900 and the present date
      col_vals_between(
        label = "Check CAMPAIGN_START_DATE is between 01 Jan 1900 and the present date",
        columns = CAMPAIGN_START_DATE,
        left = as.Date("1900-01-01"),
        right = Sys.Date(),
        actions = actions
      ) |>

      # # Check ENTERED_BY and ENTERED_DATE are not blank
      col_vals_not_null(
        label = "Check ENTERED_BY and ENTERED_DATE are not blank",
        columns = c(ENTERED_BY, ENTERED_DATE),
        actions = actions
      ) |>

      # # Check ENTERED_DATE is not in the future
      col_vals_lte(
        label = "Check ENTERED_DATE is not in the future",
        columns = ENTERED_DATE,
        value = Sys.Date(),
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Campaign",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Reference validation ----

#' @importFrom pointblank col_vals_not_null col_vals_regex col_vals_not_equal col_vals_gte col_vals_lte action_levels
#' @export
pb_validate_reference <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # # Check REFERENCE_ID exists and is the expected format
      col_vals_regex(
        label = "REFERENCE_ID is in the format YearLastnameFirstThreeWords",
        columns = REFERENCE_ID,
        # pattern matches that generated by generate_reference_id()
        regex = "^\\d{4}[A-Za-z0-9]{1,10}([A-Z][a-z]*){1,3}$",
        actions = actions
      ) |>

      # # Check REFERENCE_TYPE is in reference_type_vocabulary()
      col_vals_in_set(
        label = "REFERENCE_TYPE is in reference_type_vocabulary()",
        columns = REFERENCE_TYPE,
        set = reference_type_vocabulary(),
        actions = actions
      ) |>
      # # Check DATA_SOURCE is in data_source_vocabulary()
      col_vals_in_set(
        label = "DATA_SOURCE is in data_source_vocabulary()",
        columns = DATA_SOURCE,
        set = data_source_vocabulary(),
        actions = actions
      ) |>

      # # Check AUTHOR, TITLE are not blank
      col_vals_not_null(
        label = "Check AUTHOR, TITLE are not blank",
        columns = c(AUTHOR, TITLE),
        actions = actions
      ) |>
      # # Check YEAR is between 1900 and the current year
      col_vals_between(
        label = "Check YEAR is between 1900 and the current year",
        columns = YEAR,
        left = 1900,
        right = as.integer(format(Sys.Date(), "%Y")),
        actions = actions
      ) |>

      # # Check ACCESS_DATE is between 01 Jan 2000 and the present date
      col_vals_between(
        label = "Check ACCESS_DATE is between 01 Jan 2000 and the present date",
        columns = ACCESS_DATE,
        left = as.Date("2000-01-01"),
        right = Sys.Date(),
        actions = actions
      ) |>
      # # Check fields conditionally mandatory on REFERENCE_TYPE
      col_vals_not_null(
        label = "Check PERIODICAL_JOURNAL isn't blank when REFERENCE_TYPE is 'Journal Article'",
        preconditions = \(x) {
          x |>
            dplyr::filter(REFERENCE_TYPE == "Journal Article")
        },
        columns = PERIODICAL_JOURNAL,
        actions = actions
      ) |>
      col_vals_not_null(
        label = "Check PUBLISHER isn't blank when REFERENCE_TYPE is 'Book' or 'Report'",
        preconditions = \(x) {
          x |>
            dplyr::filter(REFERENCE_TYPE %in% c("Book", "Report"))
        },
        columns = PUBLISHER,
        actions = actions
      ) |>
      col_vals_not_null(
        label = "Check INSTITUTION isn't blank when REFERENCE_TYPE is 'Report'",
        preconditions = \(x) {
          x |>
            dplyr::filter(REFERENCE_TYPE %in% c("Report"))
        },
        columns = INSTITUTION,
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Reference",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Parameters validation ----

#' @importFrom pointblank col_vals_not_null col_vals_equal action_levels
#' @export
pb_validate_parameters <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # Core identifiers
      col_vals_not_null(columns = PARAMETER_TYPE, actions = actions) |>
      col_vals_not_null(columns = MEASURED_TYPE, actions = actions) |>
      col_vals_not_null(columns = PARAMETER_NAME, actions = actions) |>
      # FIXME: This will obviously fail on new parameters. Will need a more intelligent approach in time.
      col_vals_in_set(
        label = "Check PARAMETER_NAME in parameters_vocabulary()$PARAMETER_NAME",
        columns = PARAMETER_NAME,
        set = parameters_vocabulary() |> pull(PARAMETER_NAME),
        actions = actions
      ) |>

      # Metadata
      col_vals_not_null(columns = ENTERED_BY, actions = actions)
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Parameters",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}
# ## Sites validation ----

#' @param northern_hemisphere Logical. If TRUE, constrains latitude validation
#'   to northern hemisphere (0-90). Default is FALSE (allows -90 to 90).
#' @importFrom pointblank col_vals_not_null col_vals_in_set col_vals_between rows_distinct action_levels
#' @export
pb_validate_sites <- function(
  data,
  actions = action_levels(),
  agent = TRUE,
  northern_hemisphere = FALSE
) {
  # Set latitude bounds based on hemisphere constraint ----
  lat_min <- if (northern_hemisphere) 0 else -90
  lat_max <- 90

  apply_validations <- function(x) {
    x |>
      # # Check SITE_CODE and SITE_NAME are not blank
      col_vals_not_null(
        label = "Check SITE_CODE and SITE_NAME are not blank",
        columns = c(SITE_CODE, SITE_NAME),
        actions = actions
      ) |>

      # # Check no duplicate site code/name combinations
      rows_distinct(
        label = "Check no duplicate site code/name combinations",
        columns = c(SITE_CODE, SITE_NAME),
        actions = actions
      ) |>

      # # Check SITE_GEOGRAPHIC_FEATURE is in geographic_features_vocabulary()
      col_vals_in_set(
        label = "Check SITE_GEOGRAPHIC_FEATURE is in geographic_features_vocabulary()",
        columns = SITE_GEOGRAPHIC_FEATURE,
        set = geographic_features_vocabulary(),
        actions = actions
      ) |>

      # # Check SITE_GEOGRAPHIC_FEATURE_SUB is in geographic_features_sub_vocabulary()
      col_vals_in_set(
        label = "Check SITE_GEOGRAPHIC_FEATURE_SUB is in geographic_features_sub_vocabulary()",
        columns = SITE_GEOGRAPHIC_FEATURE_SUB,
        set = geographic_features_sub_vocabulary(),
        actions = actions
      ) |>

      # # Check COUNTRY_ISO is in countries_vocabulary()
      col_vals_in_set(
        label = "Check COUNTRY_ISO is in countries_vocabulary()",
        columns = COUNTRY_ISO,
        set = c(countries_vocabulary(), "Not reported", "Not relevant"),
        actions = actions
      ) |>

      # # Check OCEAN_IHO is in areas_vocabulary()
      col_vals_in_set(
        label = "Check OCEAN_IHO is in areas_vocabulary()",
        columns = OCEAN_IHO,
        set = c(areas_vocabulary(), "Not reported", "Not relevant"),
        actions = actions
      ) |>

      # # Check LATITUDE is within valid range
      col_vals_between(
        label = "Check LATITUDE is between {lat_min} and {lat_max}",
        columns = LATITUDE,
        left = lat_min,
        right = lat_max,
        actions = actions
      ) |>

      # # Check LONGITUDE is between -180 and 180
      col_vals_between(
        label = "Check LONGITUDE is between -180 and 180",
        columns = LONGITUDE,
        left = -180,
        right = 180,
        actions = actions
      ) |>

      # # Check SITE_COORDINATE_SYSTEM is in coordinate_systems_vocabulary()
      col_vals_in_set(
        label = "Check SITE_COORDINATE_SYSTEM is in coordinate_systems_vocabulary()",
        columns = SITE_COORDINATE_SYSTEM,
        set = coordinate_systems_vocabulary(),
        actions = actions
      ) |>

      # # Check ALTITUDE_VALUE is between -11000 and 9000
      col_vals_between(
        label = "Check ALTITUDE_VALUE is between -11000 and 9000",
        columns = ALTITUDE_VALUE,
        left = -11000,
        right = 9000,
        actions = actions
      ) |>

      # # Check ALTITUDE_UNIT is in altitude_units_vocabulary()
      col_vals_in_set(
        label = "Check ALTITUDE_UNIT is in altitude_units_vocabulary()",
        columns = ALTITUDE_UNIT,
        set = altitude_units_vocabulary(),
        actions = actions
      ) |>

      # # Check ENTERED_BY and ENTERED_DATE are not blank
      col_vals_not_null(
        label = "Check ENTERED_BY and ENTERED_DATE are not blank",
        columns = c(ENTERED_BY, ENTERED_DATE),
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Sites",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Samples validation ----

#' @importFrom pointblank col_vals_not_null col_vals_in_set action_levels
#' @importFrom purrr flatten
#' @export
pb_validate_samples <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # Core identifiers
      col_vals_not_null(columns = SAMPLE_ID, actions = actions) |>
      col_vals_not_null(columns = SITE_CODE, actions = actions) |>
      col_vals_not_null(columns = PARAMETER_NAME, actions = actions) |>

      # Environmental compartments
      # Todo: Check consistency between both
      col_vals_in_set(
        columns = ENVIRON_COMPARTMENT,
        set = environ_compartments_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = ENVIRON_COMPARTMENT_SUB,
        set = environ_compartments_sub_vocabulary() |> flatten(),
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Samples",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Biota validation ----

#' @importFrom pointblank col_vals_not_null col_vals_equal col_vals_in_set action_levels
#' @export
pb_validate_biota <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # Core identifiers
      col_vals_not_null(columns = SAMPLE_ID, actions = actions) |>
      col_vals_not_null(columns = SITE_CODE, actions = actions) |>
      col_vals_not_null(columns = PARAMETER_NAME, actions = actions) |>
      # FIXME: This will obviously fail on new parameters. Will need a more intelligent approach in time.
      col_vals_in_set(
        columns = PARAMETER_NAME,
        set = parameters_vocabulary() |> pull(PARAMETER_NAME),
        actions = actions
      ) |>

      # Biota-specific fields
      col_vals_not_null(columns = SPECIES_GROUP, actions = actions) |>
      col_vals_not_null(columns = SAMPLE_SPECIES, actions = actions) |>
      col_vals_not_null(columns = SAMPLE_TISSUE, actions = actions) |>

      # # Check environmental compartments are both some type of biota
      col_vals_equal(
        columns = ENVIRON_COMPARTMENT,
        "Biota",
        actions = actions
      ) |>
      col_vals_in_set(
        columns = ENVIRON_COMPARTMENT_SUB,
        set = environ_compartments_sub_vocabulary()$Biota,
        actions = actions
      ) |>

      # # Check group, tissue, species, gender are in the expected vocab
      col_vals_in_set(
        columns = SPECIES_GROUP,
        set = species_groups_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = SAMPLE_TISSUE,
        set = tissue_types_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = SAMPLE_SPECIES_LIFESTAGE,
        set = lifestage_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = SAMPLE_SPECIES_GENDER,
        set = gender_vocabulary(),
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Biota",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Measurements validation ----

#' @importFrom pointblank col_vals_not_null col_vals_equal col_vals_gte col_vals_lte col_vals_in_set col_vals_not_equal action_levels
#' @importFrom purrr flatten
#' @importFrom dplyr pull
#' @export
pb_validate_measurements <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # Core identifiers
      col_vals_not_null(columns = SITE_CODE, actions = actions) |>
      col_vals_not_null(columns = PARAMETER_NAME, actions = actions) |>
      # FIXME: This will obviously fail on new parameters. Will need a more intelligent approach in time.
      col_vals_in_set(
        columns = PARAMETER_NAME,
        set = parameters_vocabulary() |> pull(PARAMETER_NAME),
        actions = actions
      ) |>
      col_vals_not_null(columns = SAMPLING_DATE, actions = actions) |>
      col_vals_gte(
        columns = SAMPLING_DATE,
        value = as.Date("1900-01-01"),
        actions = actions
      ) |>
      col_vals_lte(
        columns = SAMPLING_DATE,
        value = Sys.Date(),
        actions = actions
      ) |>

      # TODO: Subset by measured flag so we can properly check LOD, LOQ, etc.
      # Environmental compartments
      col_vals_in_set(
        columns = ENVIRON_COMPARTMENT,
        set = environ_compartments_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = ENVIRON_COMPARTMENT_SUB,
        set = environ_compartments_sub_vocabulary() |> flatten(),
        actions = actions
      ) |>

      # # Measurement values
      col_vals_in_set(
        label = "Check MEASURED_FLAG is blank, '< LOQ' or '< LOD'",
        columns = MEASURED_FLAG,
        set = measured_flag_vocabulary(),
        actions = actions
      ) |>
      # # When MEASURED_FLAG is blank, check we have a MEASURED_VALUE and valid MEASURED_UNIT
      col_vals_not_null(
        label = "When MEASURED_FLAG is blank, check MEASURED_VALUE isn't null",
        preconditions = \(x) x |> dplyr::filter(MEASURED_FLAG == ""),
        columns = MEASURED_VALUE,
        actions = actions
      ) |>
      col_vals_in_set(
        label = "When MEASURED_FLAG is blank, check MEASURED_UNIT is in parameter_unit_vocabulary()",
        preconditions = \(x) x |> dplyr::filter(MEASURED_FLAG == ""),
        columns = MEASURED_UNIT,
        set = parameter_unit_vocabulary() |> pull(MEASURED_UNIT),
        actions = actions
      ) |>
      # # Check MEASURED_N >= 1
      col_vals_gte(
        label = "Check MEASURED_N >= 1",
        columns = MEASURED_N,
        value = 1,
        actions = actions
      ) |>
      # # Check that UNCERTAINTY_TYPE is in uncertainty_types_vocabulary()
      col_vals_in_set(
        label = "Check that UNCERTAINTY_TYPE is in uncertainty_types_vocabulary()",
        columns = UNCERTAINTY_TYPE,
        set = uncertainty_types_vocabulary(),
        actions = actions
      ) |>

      # TODO: Validate MEASURED_TYPE
      # TODO: Validate Extraction, Analytical, Fractionation, Sampling protocol match regex
      # TODO: Conditionally check LOD units

      # # LOQ/LOD values
      col_vals_gte(
        columns = LOQ_VALUE,
        value = 0,
        actions = actions
      ) |>
      col_vals_gte(
        columns = LOD_VALUE,
        value = 0,
        actions = actions
      ) |>

      # TODO: Check REFERENCE_ID matches regex and isn't Unknown
      col_vals_not_null(columns = REFERENCE_ID, actions = actions) |>
      col_vals_not_equal(
        columns = REFERENCE_ID,
        value = "Unknown Reference",
        actions = actions
      ) |>
      # TODO: Check SAMPLE_ID matches regex
      col_vals_not_null(columns = SAMPLE_ID, actions = actions)
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Measurements",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Methods validation ----

#' @importFrom pointblank col_vals_not_null col_vals_in_set action_levels
#' @importFrom dplyr pull
#' @export
pb_validate_methods <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  apply_validations <- function(x) {
    x |>
      # TODO: Check protocol ID against regex
      col_vals_not_null(
        columns = c(PROTOCOL_ID, CAMPAIGN_NAME),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = PROTOCOL_CATEGORY,
        set = protocol_categories_vocabulary(),
        actions = actions
      ) |>
      col_vals_in_set(
        columns = PROTOCOL_NAME,
        set = protocol_options_vocabulary() |> pull(Long_Name),
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "Methods",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## CREED Scores validation ----

#' @importFrom pointblank col_vals_not_null col_vals_not_equal col_vals_in_set action_levels
#' @export
pb_validate_creed_scores <- function(
  data,
  actions = action_levels(),
  agent = TRUE
) {
  CREED_classifications_rb <- c(
    "Not usable",
    "Reliable with restrictions",
    "Reliable without restrictions"
  )
  CREED_classifications_rv <- c(
    "Not usable",
    "Relevant with restrictions",
    "Relevant without restrictions"
  )

  apply_validations <- function(x) {
    x |>
      # Core identifiers
      # TODO: Check REFERENCE_ID against regex

      col_vals_not_null(columns = REFERENCE_ID, actions = actions) |>
      col_vals_not_equal(
        columns = REFERENCE_ID,
        value = "Unknown Reference",
        actions = actions
      ) |>

      # CREED fields
      col_vals_in_set(
        columns = c(SILVER_RELIABILITY, GOLD_RELIABILITY),
        set = CREED_classifications_rb,
        actions = actions
      ) |>
      col_vals_in_set(
        columns = c(SILVER_RELEVANCE, GOLD_RELEVANCE),
        set = CREED_classifications_rv,
        actions = actions
      )
  }

  pb_validate_edata_table(
    data = data,
    table_name = "CREED Scores",
    validation_steps = apply_validations,
    agent = agent,
    actions = actions
  )
}

# ## Validate all tables ----
#' Validate all eData tables at once
#'
#' @param campaign Campaign table
#' @param reference Reference table
#' @param parameters Parameters table
#' @param sites Sites table
#' @param samples Samples table (optional)
#' @param biota Biota table (optional)
#' @param measurements Measurements table
#' @param methods Methods table (optional)
#' @param creed_scores CREED Scores table (optional)
#' @param actions Action levels for pointblank agents (only used when agent = TRUE)
#' @param agent Logical. If TRUE (default), returns a list of pointblank agent objects.
#'   If FALSE, returns a list of validated data frames with failures removed.
#' @param northern_hemisphere Logical. If TRUE, check that site coordinates are in northern hemisphere.
#'
#' @return If agent = TRUE, a named list of pointblank agent objects.
#'   If agent = FALSE, a named list of validated data frames.
#' @export
pb_validate_all_edata_tables <- function(
  campaign,
  reference,
  parameters,
  sites,
  samples = NULL,
  biota = NULL,
  measurements,
  methods = NULL,
  creed_scores = NULL,
  actions = action_levels(),
  agent = TRUE,
  northern_hemisphere = FALSE
) {
  results <- list(
    campaign = pb_validate_campaign(campaign, actions, agent),
    reference = pb_validate_reference(reference, actions, agent),
    parameters = pb_validate_parameters(parameters, actions, agent),
    sites = pb_validate_sites(sites, actions, agent, northern_hemisphere),
    measurements = pb_validate_measurements(measurements, actions, agent)
  )

  # Add optional tables if provided
  if (!is.null(samples)) {
    results$samples <- pb_validate_samples(samples, actions, agent)
  }

  if (!is.null(biota)) {
    results$biota <- pb_validate_biota(biota, actions, agent)
  }

  if (!is.null(methods)) {
    results$methods <- pb_validate_methods(methods, actions, agent)
  }

  if (!is.null(creed_scores)) {
    results$creed_scores <- pb_validate_creed_scores(
      creed_scores,
      actions,
      agent
    )
  }

  return(results)
}


#' Wrapper for col_vals_in_set with enhanced error reporting
#'
#' @param x A data table
#' @param columns Column(s) to validate
#' @param set Valid set of values
#' @param actions Action levels for pointblank
#' @param value_name Optional name to describe what the values represent (e.g., "Reference IDs")
#'
#' @return The validated data table
#' @importFrom pointblank col_vals_in_set action_levels
#' @importFrom dplyr filter pull
#' @importFrom rlang as_name enquo
#' @export
col_vals_in_set_verbose <- function(
  x,
  columns,
  set,
  actions,
  value_name = NULL
) {
  `%notin%` <- Negate(`%in%`)
  # Capture the column name for reporting
  col_name <- rlang::as_name(rlang::enquo(columns))

  # Find missing values before validation
  missing_vals <- x |>
    filter({{ columns }} %notin% set) |>
    pull({{ columns }}) |>
    unique()

  # Run the validation
  result <- col_vals_in_set(
    x,
    columns = {{ columns }},
    set = set,
    actions = actions
  )

  # If there are missing values, issue a detailed warning
  if (length(missing_vals) > 0) {
    value_desc <- if (!is.null(value_name)) value_name else col_name
    warning(
      sprintf(
        "%s not found in reference set: %s",
        value_desc,
        paste(missing_vals, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  result
}
